[2023-11-10T10:39:48.146+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: rand_user.load_upload_data manual__2023-11-10T10:39:46.058446+00:00 [queued]>
[2023-11-10T10:39:48.166+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: rand_user.load_upload_data manual__2023-11-10T10:39:46.058446+00:00 [queued]>
[2023-11-10T10:39:48.166+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-11-10T10:39:48.167+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 3
[2023-11-10T10:39:48.167+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-11-10T10:39:48.220+0000] {taskinstance.py:1383} INFO - Executing <Task(GenericTransfer): load_upload_data> on 2023-11-10 10:39:46.058446+00:00
[2023-11-10T10:39:48.235+0000] {standard_task_runner.py:55} INFO - Started process 4069 to run task
[2023-11-10T10:39:48.249+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'rand_user', 'load_upload_data', 'manual__2023-11-10T10:39:46.058446+00:00', '--job-id', '157', '--raw', '--subdir', 'DAGS_FOLDER/predictions.py', '--cfg-path', '/tmp/tmpwpl41ro7']
[2023-11-10T10:39:48.256+0000] {standard_task_runner.py:83} INFO - Job 157: Subtask load_upload_data
[2023-11-10T10:39:48.369+0000] {task_command.py:376} INFO - Running <TaskInstance: rand_user.load_upload_data manual__2023-11-10T10:39:46.058446+00:00 [running]> on host 91f7624ceef9
[2023-11-10T10:39:48.502+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Gaurav
AIRFLOW_CTX_DAG_ID=rand_user
AIRFLOW_CTX_TASK_ID=load_upload_data
AIRFLOW_CTX_EXECUTION_DATE=2023-11-10T10:39:46.058446+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-10T10:39:46.058446+00:00
[2023-11-10T10:39:48.516+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-11-10T10:39:48.867+0000] {base.py:71} INFO - Using connection ID 'Destination_table' for task execution.
[2023-11-10T10:39:49.209+0000] {generic_transfer.py:76} INFO - Extracting data from postgres
[2023-11-10T10:39:49.210+0000] {generic_transfer.py:77} INFO - Executing: 
 select * from rand_users
[2023-11-10T10:39:49.223+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-11-10T10:39:49.244+0000] {generic_transfer.py:94} INFO - Running preoperator
[2023-11-10T10:39:49.245+0000] {generic_transfer.py:95} INFO - TRUNCATE TABLE datamart.tags
[2023-11-10T10:39:49.263+0000] {base.py:71} INFO - Using connection ID 'Destination_table' for task execution.
[2023-11-10T10:39:49.277+0000] {sql.py:315} INFO - Running statement: TRUNCATE TABLE datamart.tags, parameters: None
[2023-11-10T10:39:49.288+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/generic_transfer.py", line 96, in execute
    run(self.preoperator)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 295, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 320, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InvalidSchemaName: schema "datamart" does not exist

[2023-11-10T10:39:49.324+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=rand_user, task_id=load_upload_data, execution_date=20231110T103946, start_date=20231110T103948, end_date=20231110T103949
[2023-11-10T10:39:49.357+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 157 for task load_upload_data (schema "datamart" does not exist
; 4069)
[2023-11-10T10:39:49.415+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-11-10T10:39:49.462+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
