[2023-11-22T05:48:16.003+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: rand_user.upload_data_source manual__2023-11-22T05:45:53.844169+00:00 [queued]>
[2023-11-22T05:48:16.022+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: rand_user.upload_data_source manual__2023-11-22T05:45:53.844169+00:00 [queued]>
[2023-11-22T05:48:16.022+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-11-22T05:48:16.023+0000] {taskinstance.py:1363} INFO - Starting attempt 3 of 3
[2023-11-22T05:48:16.024+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-11-22T05:48:16.057+0000] {taskinstance.py:1383} INFO - Executing <Task(GenericTransfer): upload_data_source> on 2023-11-22 05:45:53.844169+00:00
[2023-11-22T05:48:16.070+0000] {standard_task_runner.py:55} INFO - Started process 6408 to run task
[2023-11-22T05:48:16.079+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'rand_user', 'upload_data_source', 'manual__2023-11-22T05:45:53.844169+00:00', '--job-id', '747', '--raw', '--subdir', 'DAGS_FOLDER/predictions.py', '--cfg-path', '/tmp/tmpyepv1ftt']
[2023-11-22T05:48:16.083+0000] {standard_task_runner.py:83} INFO - Job 747: Subtask upload_data_source
[2023-11-22T05:48:16.198+0000] {task_command.py:376} INFO - Running <TaskInstance: rand_user.upload_data_source manual__2023-11-22T05:45:53.844169+00:00 [running]> on host 91f7624ceef9
[2023-11-22T05:48:16.330+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Gaurav
AIRFLOW_CTX_DAG_ID=rand_user
AIRFLOW_CTX_TASK_ID=upload_data_source
AIRFLOW_CTX_EXECUTION_DATE=2023-11-22T05:45:53.844169+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-22T05:45:53.844169+00:00
[2023-11-22T05:48:16.346+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-11-22T05:48:16.690+0000] {base.py:71} INFO - Using connection ID 'source_db_***' for task execution.
[2023-11-22T05:48:16.998+0000] {generic_transfer.py:76} INFO - Extracting data from postgres
[2023-11-22T05:48:16.998+0000] {generic_transfer.py:77} INFO - Executing: 
 SELECT * FROM rand_users
[2023-11-22T05:48:17.009+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-11-22T05:48:17.016+0000] {generic_transfer.py:94} INFO - Running preoperator
[2023-11-22T05:48:17.017+0000] {generic_transfer.py:95} INFO - TRUNCATE TABLE rand_users
[2023-11-22T05:48:17.027+0000] {base.py:71} INFO - Using connection ID 'source_db_***' for task execution.
[2023-11-22T05:48:17.048+0000] {sql.py:315} INFO - Running statement: TRUNCATE TABLE rand_users, parameters: None
[2023-11-22T05:48:17.660+0000] {generic_transfer.py:104} INFO - Inserting rows into source_db_***
[2023-11-22T05:48:17.670+0000] {base.py:71} INFO - Using connection ID 'source_db_***' for task execution.
[2023-11-22T05:48:17.682+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/generic_transfer.py", line 105, in execute
    insert_rows(table=self.destination_table, rows=results, **self.insert_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 409, in insert_rows
    cur.execute(sql, values)
psycopg2.errors.NotNullViolation: null value in column "age" violates not-null constraint
DETAIL:  Failing row contains (male, Mr, Vincent, Ross, Canada, whiteelephant503, peter, vincent.ross@example.com, 38, null).

[2023-11-22T05:48:17.698+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=rand_user, task_id=upload_data_source, execution_date=20231122T054553, start_date=20231122T054816, end_date=20231122T054817
[2023-11-22T05:48:17.731+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 747 for task upload_data_source (null value in column "age" violates not-null constraint
DETAIL:  Failing row contains (male, Mr, Vincent, Ross, Canada, whiteelephant503, peter, vincent.ross@example.com, 38, null).
; 6408)
[2023-11-22T05:48:17.776+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-11-22T05:48:17.823+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
