[2023-11-22T05:55:37.905+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: rand_user.store_user manual__2023-11-22T05:54:25.135106+00:00 [queued]>
[2023-11-22T05:55:37.929+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: rand_user.store_user manual__2023-11-22T05:54:25.135106+00:00 [queued]>
[2023-11-22T05:55:37.930+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-11-22T05:55:37.930+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 3
[2023-11-22T05:55:37.930+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-11-22T05:55:37.973+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): store_user> on 2023-11-22 05:54:25.135106+00:00
[2023-11-22T05:55:37.985+0000] {standard_task_runner.py:55} INFO - Started process 6792 to run task
[2023-11-22T05:55:37.992+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'rand_user', 'store_user', 'manual__2023-11-22T05:54:25.135106+00:00', '--job-id', '767', '--raw', '--subdir', 'DAGS_FOLDER/predictions.py', '--cfg-path', '/tmp/tmpxynqv562']
[2023-11-22T05:55:37.996+0000] {standard_task_runner.py:83} INFO - Job 767: Subtask store_user
[2023-11-22T05:55:38.101+0000] {task_command.py:376} INFO - Running <TaskInstance: rand_user.store_user manual__2023-11-22T05:54:25.135106+00:00 [running]> on host 91f7624ceef9
[2023-11-22T05:55:38.248+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Gaurav
AIRFLOW_CTX_DAG_ID=rand_user
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2023-11-22T05:54:25.135106+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-22T05:54:25.135106+00:00
[2023-11-22T05:55:38.250+0000] {postgres.py:129} INFO - Running copy expert: COPY rand_users FROM stdin WITH DELIMITER as ',', filename: /tmp/processed_user.csv
[2023-11-22T05:55:38.265+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-11-22T05:55:38.274+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/predictions.py", line 38, in _store_user
    filename='/tmp/processed_user.csv'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 137, in copy_expert
    cur.copy_expert(sql, file)
psycopg2.errors.BadCopyFileFormat: missing data for column "age"
CONTEXT:  COPY rand_users, line 1: "male,Mr,Ariosto,Aragão,Brazil,ticklishsnake760,grand,ariosto.aragao@example.com"

[2023-11-22T05:55:38.292+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=rand_user, task_id=store_user, execution_date=20231122T055425, start_date=20231122T055537, end_date=20231122T055538
[2023-11-22T05:55:38.316+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 767 for task store_user (missing data for column "age"
CONTEXT:  COPY rand_users, line 1: "male,Mr,Ariosto,Aragão,Brazil,ticklishsnake760,grand,ariosto.aragao@example.com"
; 6792)
[2023-11-22T05:55:38.364+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-11-22T05:55:38.435+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
