[2023-11-22T05:06:26.183+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: rand_user.upload_data_source manual__2023-11-22T05:05:08.848057+00:00 [queued]>
[2023-11-22T05:06:26.201+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: rand_user.upload_data_source manual__2023-11-22T05:05:08.848057+00:00 [queued]>
[2023-11-22T05:06:26.202+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-11-22T05:06:26.202+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 3
[2023-11-22T05:06:26.203+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-11-22T05:06:26.239+0000] {taskinstance.py:1383} INFO - Executing <Task(GenericTransfer): upload_data_source> on 2023-11-22 05:05:08.848057+00:00
[2023-11-22T05:06:26.250+0000] {standard_task_runner.py:55} INFO - Started process 4258 to run task
[2023-11-22T05:06:26.257+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'rand_user', 'upload_data_source', 'manual__2023-11-22T05:05:08.848057+00:00', '--job-id', '603', '--raw', '--subdir', 'DAGS_FOLDER/predictions.py', '--cfg-path', '/tmp/tmpf2yq9z1w']
[2023-11-22T05:06:26.260+0000] {standard_task_runner.py:83} INFO - Job 603: Subtask upload_data_source
[2023-11-22T05:06:26.390+0000] {task_command.py:376} INFO - Running <TaskInstance: rand_user.upload_data_source manual__2023-11-22T05:05:08.848057+00:00 [running]> on host 91f7624ceef9
[2023-11-22T05:06:26.518+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Gaurav
AIRFLOW_CTX_DAG_ID=rand_user
AIRFLOW_CTX_TASK_ID=upload_data_source
AIRFLOW_CTX_EXECUTION_DATE=2023-11-22T05:05:08.848057+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-22T05:05:08.848057+00:00
[2023-11-22T05:06:26.535+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-11-22T05:06:26.881+0000] {base.py:71} INFO - Using connection ID 'source_db_***' for task execution.
[2023-11-22T05:06:27.245+0000] {generic_transfer.py:76} INFO - Extracting data from postgres
[2023-11-22T05:06:27.245+0000] {generic_transfer.py:77} INFO - Executing: 
 SELECT * FROM rand_users
[2023-11-22T05:06:27.256+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-11-22T05:06:27.264+0000] {generic_transfer.py:104} INFO - Inserting rows into source_db_***
[2023-11-22T05:06:27.274+0000] {base.py:71} INFO - Using connection ID 'source_db_***' for task execution.
[2023-11-22T05:06:27.286+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/generic_transfer.py", line 105, in execute
    insert_rows(table=self.destination_table, rows=results, **self.insert_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 409, in insert_rows
    cur.execute(sql, values)
psycopg2.errors.NotNullViolation: null value in column "age" violates not-null constraint
DETAIL:  Failing row contains (male, Mr, Vincent, Ross, Canada, whiteelephant503, peter, vincent.ross@example.com, 38, null).

[2023-11-22T05:06:27.299+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=rand_user, task_id=upload_data_source, execution_date=20231122T050508, start_date=20231122T050626, end_date=20231122T050627
[2023-11-22T05:06:27.329+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 603 for task upload_data_source (null value in column "age" violates not-null constraint
DETAIL:  Failing row contains (male, Mr, Vincent, Ross, Canada, whiteelephant503, peter, vincent.ross@example.com, 38, null).
; 4258)
[2023-11-22T05:06:27.351+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-11-22T05:06:27.391+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
