[2023-11-22T05:19:17.203+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: rand_user.upload_data_source manual__2023-11-22T05:19:03.780438+00:00 [queued]>
[2023-11-22T05:19:17.223+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: rand_user.upload_data_source manual__2023-11-22T05:19:03.780438+00:00 [queued]>
[2023-11-22T05:19:17.223+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-11-22T05:19:17.224+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 3
[2023-11-22T05:19:17.225+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-11-22T05:19:17.253+0000] {taskinstance.py:1383} INFO - Executing <Task(GenericTransfer): upload_data_source> on 2023-11-22 05:19:03.780438+00:00
[2023-11-22T05:19:17.263+0000] {standard_task_runner.py:55} INFO - Started process 4936 to run task
[2023-11-22T05:19:17.270+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'rand_user', 'upload_data_source', 'manual__2023-11-22T05:19:03.780438+00:00', '--job-id', '643', '--raw', '--subdir', 'DAGS_FOLDER/predictions.py', '--cfg-path', '/tmp/tmpcoa6bwyz']
[2023-11-22T05:19:17.273+0000] {standard_task_runner.py:83} INFO - Job 643: Subtask upload_data_source
[2023-11-22T05:19:17.383+0000] {task_command.py:376} INFO - Running <TaskInstance: rand_user.upload_data_source manual__2023-11-22T05:19:03.780438+00:00 [running]> on host 91f7624ceef9
[2023-11-22T05:19:17.524+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Gaurav
AIRFLOW_CTX_DAG_ID=rand_user
AIRFLOW_CTX_TASK_ID=upload_data_source
AIRFLOW_CTX_EXECUTION_DATE=2023-11-22T05:19:03.780438+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-22T05:19:03.780438+00:00
[2023-11-22T05:19:17.540+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-11-22T05:19:17.932+0000] {base.py:71} INFO - Using connection ID 'source_db_***' for task execution.
[2023-11-22T05:19:18.225+0000] {generic_transfer.py:76} INFO - Extracting data from postgres
[2023-11-22T05:19:18.225+0000] {generic_transfer.py:77} INFO - Executing: 
 SELECT * FROM rand_users
[2023-11-22T05:19:18.235+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-11-22T05:19:18.243+0000] {generic_transfer.py:104} INFO - Inserting rows into source_db_***
[2023-11-22T05:19:18.252+0000] {base.py:71} INFO - Using connection ID 'source_db_***' for task execution.
[2023-11-22T05:19:18.263+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/generic_transfer.py", line 105, in execute
    insert_rows(table=self.destination_table, rows=results, **self.insert_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 409, in insert_rows
    cur.execute(sql, values)
psycopg2.errors.NotNullViolation: null value in column "age" violates not-null constraint
DETAIL:  Failing row contains (male, Mr, Vincent, Ross, Canada, whiteelephant503, peter, vincent.ross@example.com, 38, null).

[2023-11-22T05:19:18.280+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=rand_user, task_id=upload_data_source, execution_date=20231122T051903, start_date=20231122T051917, end_date=20231122T051918
[2023-11-22T05:19:18.312+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 643 for task upload_data_source (null value in column "age" violates not-null constraint
DETAIL:  Failing row contains (male, Mr, Vincent, Ross, Canada, whiteelephant503, peter, vincent.ross@example.com, 38, null).
; 4936)
[2023-11-22T05:19:18.364+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-11-22T05:19:18.406+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
