[2023-11-23T07:07:54.866+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: rand_user.store_user scheduled__2023-11-23T06:51:44.757059+00:00 [queued]>
[2023-11-23T07:07:54.878+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: rand_user.store_user scheduled__2023-11-23T06:51:44.757059+00:00 [queued]>
[2023-11-23T07:07:54.879+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-11-23T07:07:54.879+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 3
[2023-11-23T07:07:54.879+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-11-23T07:07:54.896+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): store_user> on 2023-11-23 06:51:44.757059+00:00
[2023-11-23T07:07:54.904+0000] {standard_task_runner.py:55} INFO - Started process 9178 to run task
[2023-11-23T07:07:54.908+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'rand_user', 'store_user', 'scheduled__2023-11-23T06:51:44.757059+00:00', '--job-id', '608', '--raw', '--subdir', 'DAGS_FOLDER/predictions.py', '--cfg-path', '/tmp/tmprfuzfmka']
[2023-11-23T07:07:54.911+0000] {standard_task_runner.py:83} INFO - Job 608: Subtask store_user
[2023-11-23T07:07:54.983+0000] {task_command.py:376} INFO - Running <TaskInstance: rand_user.store_user scheduled__2023-11-23T06:51:44.757059+00:00 [running]> on host f71f95879a41
[2023-11-23T07:07:55.069+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Gaurav
AIRFLOW_CTX_DAG_ID=rand_user
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2023-11-23T06:51:44.757059+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-23T06:51:44.757059+00:00
[2023-11-23T07:07:55.071+0000] {postgres.py:129} INFO - Running copy expert: COPY rand_users FROM stdin WITH DELIMITER as ',' , filename: /tmp/processed_user.csv
[2023-11-23T07:07:55.081+0000] {base.py:71} INFO - Using connection ID 'source_db_***' for task execution.
[2023-11-23T07:07:55.093+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/predictions.py", line 47, in _store_user
    filename='/tmp/processed_user.csv'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 137, in copy_expert
    cur.copy_expert(sql, file)
psycopg2.errors.BadCopyFileFormat: missing data for column "inserted_at"
CONTEXT:  COPY rand_users, line 1: "9f249f5e-469a-49bd-b85f-24ab95551531,male,Mr,Kirk,Young,Australia,greenzebra267,leanne,kirk.young@ex..."

[2023-11-23T07:07:55.116+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=rand_user, task_id=store_user, execution_date=20231123T065144, start_date=20231123T070754, end_date=20231123T070755
[2023-11-23T07:07:55.139+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 608 for task store_user (missing data for column "inserted_at"
CONTEXT:  COPY rand_users, line 1: "9f249f5e-469a-49bd-b85f-24ab95551531,male,Mr,Kirk,Young,Australia,greenzebra267,leanne,kirk.young@ex..."
; 9178)
[2023-11-23T07:07:55.159+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-11-23T07:07:55.206+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
