[2023-11-10T04:43:45.204+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: US_population.process_user manual__2023-11-10T04:43:37.908025+00:00 [queued]>
[2023-11-10T04:43:45.216+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: US_population.process_user manual__2023-11-10T04:43:37.908025+00:00 [queued]>
[2023-11-10T04:43:45.217+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-11-10T04:43:45.217+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 3
[2023-11-10T04:43:45.217+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-11-10T04:43:45.233+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): process_user> on 2023-11-10 04:43:37.908025+00:00
[2023-11-10T04:43:45.239+0000] {standard_task_runner.py:55} INFO - Started process 1452 to run task
[2023-11-10T04:43:45.244+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'US_population', 'process_user', 'manual__2023-11-10T04:43:37.908025+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/predictions.py', '--cfg-path', '/tmp/tmphphlq843']
[2023-11-10T04:43:45.246+0000] {standard_task_runner.py:83} INFO - Job 91: Subtask process_user
[2023-11-10T04:43:45.312+0000] {task_command.py:376} INFO - Running <TaskInstance: US_population.process_user manual__2023-11-10T04:43:37.908025+00:00 [running]> on host 91f7624ceef9
[2023-11-10T04:43:45.382+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Gaurav
AIRFLOW_CTX_DAG_ID=US_population
AIRFLOW_CTX_TASK_ID=process_user
AIRFLOW_CTX_EXECUTION_DATE=2023-11-10T04:43:37.908025+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-10T04:43:37.908025+00:00
[2023-11-10T04:43:45.395+0000] {logging_mixin.py:120} INFO - Printing the user data: []
[2023-11-10T04:43:45.395+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/predictions.py", line 33, in _process_user
    'ID_Nation': user_list['ID Nation'],
TypeError: list indices must be integers or slices, not str
[2023-11-10T04:43:45.407+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=US_population, task_id=process_user, execution_date=20231110T044337, start_date=20231110T044345, end_date=20231110T044345
[2023-11-10T04:43:45.420+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 91 for task process_user (list indices must be integers or slices, not str; 1452)
[2023-11-10T04:43:45.455+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-11-10T04:43:45.481+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
